# Generated by Django 3.2.12 on 2023-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230427_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='area',
            new_name='state',
        ),
    ]
